default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit, pre-push, manual]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        name: ruff-lint
        args: ["--fix"]
        types: [python]
      - id: ruff-format
        name: ruff-format
        types: [python]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        types: [python]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.336
    hooks:
      - id: pyright
        stages: [pre-commit, pre-push]
        args: ["--pythonversion", "3.11"]
